esphome:
  name: rgbww
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: "Jesse"
  password: "xxx"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Rgbww Fallback Hotspot"
    password: "Z8O4xum64VVF"

captive_portal:

web_server:
  port: 80 

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

light:
  - platform: rgbww
    name: "Livingroom Lights"
    red: pwm_r
    green:  pwm_g
    blue: pwm_b
    cold_white: pwm_w
    warm_white: pwm_ww
    cold_white_color_temperature: 6536 K
    warm_white_color_temperature: 2000 K
    
output:
  - platform: esp8266_pwm
    pin: 12
    frequency: 1000 Hz
    id: pwm_b
  - platform: esp8266_pwm
    pin: 13
    frequency: 1000 Hz
    id: pwm_g
  - platform: esp8266_pwm
    pin: 15
    frequency: 1000 Hz
    id: pwm_r
  - platform: esp8266_pwm
    pin: 14
    frequency: 1000 Hz
    id: pwm_w 
  - platform: esp8266_pwm
    pin: 4
    frequency: 1000 Hz
    id: pwm_ww